name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.STATS_TOKEN }}

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: sameer2506
          BRANCH_NAME: main
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}