name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: sameer2506
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}
